
language: node_js

node_js:
- '12'

services:
  - mongodb

before_install:
- npm update

install:
- npm install

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
- npm test

